# version of docker, been the same for years
version: "3.9"
services:
  #name of the container/service
  simcontainer-web:
    build:
      #source code for the application
      context: .
      # file the containing the build instructions
      dockerfile: Dockerfile

    # name of the image built by Dockerfile
    image: indevelopme-simcontainer-image

    # container environment settings
    environment:
      - PORT=80

    # the point of this volume is to prevent the requirement to run
    # docker-compose up --build after every change to docker-compose.yml
    volumes:
        - staticfiles:/app/static/
        - logvolume01:/var/log

    ports:
      - "8000:80"

volumes:
  logvolume01: {}
  staticfiles:
    external: true
