name: indevelopme-simlite-github-actions

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # nmae of job = "build"
  build:
    # the job runs on "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make Staticfile volumne
        run: docker volume create --name=staticfiles

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

