name: indevelopme-simlite-github-actions

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # nmae of job = "build"
  build:
    # the job runs on "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      runs:
        using: 'docker'
        image: 'Dockerfile'
