name: indevelopme-simlite-github-actions

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # nmae of job = "build"
  build:
    # the job runs on "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
      # checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # run docker-compose
      - name: Run Docker Compose
        run: |
          docker volume create --name=staticfiles
          docker-compose -f "docker-compose.yml" up -d --build

